# -*- coding: utf-8 -*-
"""python with regex.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11qM4TWgzEqaxkZ0X6TB3LhB_SnMDbfsZ
"""

from os import linesep
import re

#open the file 
with open('Text_file.txt') as txt:     
    lines = txt.read()       
    print(lines)

#empty list for store the data
gmail=[]
Bd_phn=[]

#extract gmails
email = r'[0-9a-zA-Z]+@gmail.com'
matches = re.findall(email,lines)

#extract bd phn numbers
phn_no = r'\+880[0-9]{10}' 
matche = re.findall(phn_no, lines)


for email in matches:
    gmail.append(email)

for phn_no in matche:
    Bd_phn.append(phn_no)


#store the gmail id into a file
with open('gmail_id.txt', 'w') as output:
  for i in gmail :
        output.write("%s\n" % i)

#store the phone numbers into a file
with open('Bd_mobile.txt', 'w') as output_phn:
  for j in Bd_phn:
        output_phn.write("%s\n" % j)